# Generated by Django 5.0.6 on 2024-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isrsvp',
            field=models.BooleanField(default=False),
        ),
    ]
